version: "3"

services:
  app:
    build: .
    container_name: tools-api
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - .:/home/node/code

  mongo:
    image: mongo:4
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:4-alpine
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
