version: 2.1

jobs:
  build-and-test:
    working_directory: ~/app
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Deps
          command: |
            docker-compose build
            docker-compose run --rm app npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint Commits
          command: npx commitlint-circle
      - run:
          name: Lint Code
          command: docker-compose run --rm --no-deps app npm run lint
      - run:
          name: Run Tests
          command: docker-compose run --rm --no-deps app npm run test
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run Test Coverage
          command: |
            ./cc-test-reporter before-build
            docker-compose run --rm --no-deps app npm run coverage
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
      - store_artifacts:
          path: coverage.tar.gz

workflows:
    build-and-test:
      jobs:
        - build-and-test
